// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCs5pJpUAmZAVXthiEkQST13XnO_sneM',
    appId: '1:194759112633:web:8aecdeb1b54affa8c2e868',
    messagingSenderId: '194759112633',
    projectId: 'nutriscan-565df',
    authDomain: 'nutriscan-565df.firebaseapp.com',
    databaseURL: 'https://nutriscan-565df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutriscan-565df.firebasestorage.app',
    measurementId: 'G-6PPR1F7FM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHWS9itrG9fcs7-TpE5zaBxvr7E-8oJFo',
    appId: '1:194759112633:android:ffb29cf661a3e97dc2e868',
    messagingSenderId: '194759112633',
    projectId: 'nutriscan-565df',
    databaseURL: 'https://nutriscan-565df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutriscan-565df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBat8aozUv_ddIse5IJtM4QJqS_17uhHtk',
    appId: '1:194759112633:ios:85288e8ea308d0f4c2e868',
    messagingSenderId: '194759112633',
    projectId: 'nutriscan-565df',
    databaseURL: 'https://nutriscan-565df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutriscan-565df.firebasestorage.app',
    iosBundleId: 'com.cybash.projects.nutriScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBat8aozUv_ddIse5IJtM4QJqS_17uhHtk',
    appId: '1:194759112633:ios:85288e8ea308d0f4c2e868',
    messagingSenderId: '194759112633',
    projectId: 'nutriscan-565df',
    databaseURL: 'https://nutriscan-565df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutriscan-565df.firebasestorage.app',
    iosBundleId: 'com.cybash.projects.nutriScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALCs5pJpUAmZAVXthiEkQST13XnO_sneM',
    appId: '1:194759112633:web:de699289e4a47865c2e868',
    messagingSenderId: '194759112633',
    projectId: 'nutriscan-565df',
    authDomain: 'nutriscan-565df.firebaseapp.com',
    databaseURL: 'https://nutriscan-565df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutriscan-565df.firebasestorage.app',
    measurementId: 'G-E9TJ5HSX1S',
  );
}
